apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-root-app
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: cd-root-app
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cd-root
    repoURL: https://github.com/lenthenum/user-management.git
    targetRevision: {{ .Values.deploy.revision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true