apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    path: helm/sealed-secrets
    repoURL: https://github.com/bitnami-labs/sealed-secrets
    targetRevision: v0.36.0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealed-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    managed-by: argocd